### ISSUE TITLE
Request: separate settings for VAB/SPH, and Pad/Runway

### ISSUE THREAD

**Issue by NathanKell** [sarbian/CustomBarnKit#1]
as it says on the tin.

**Comment by NathanKell** [comment]
I should clarify: costs are per building, but the AG unlock, mass limits, size limits, and part limits are universal.

**Comment by sarbian** [comment]
The stock code does not allow to separate those :(

**Comment by NathanKell** [comment]
Can you not detect what scene (or if launching from space center, GUI window) is open/active?

**Comment by sarbian** [comment]
I had a look when you first asked and the space center screen is the main problem. I'll see how I can detect which screen is opened when the call is made.
The vessel size test (and most other I guess) is called in 5 places. 2 are in the editor (launch and engineer reports) and 2 in the space center (building upgrade window and launch) and a an other I am not sure of.

**Comment by sarbian** [comment]
To add to that : I'll see if I can make it work but I am not keen on doing work dependent on UI elements that will be gone in the next version. 
We should petition Squad to have those call include a building type or have a different call for each.

**Comment by NathanKell** [comment]
That makes perfect sense. Put something on the Corner tracker?
