### ISSUE TITLE
Request: Craft size limits go with VAB/SPH not pad/runway

### ISSUE THREAD

**Issue by NathanKell** [sarbian/CustomBarnKit#3]
Suggestion: a 'useBuilding' flag, default to false.
Then change https://github.com/sarbian/CustomBarnKit/blob/master/CustomGameVariables.cs#L359 to:
int levels = useBuilding ? 
( isPad ? levelsVAB : levelsSPH)
: (isPad ? levelsLaunchPad : levelsRunway);

and https://github.com/sarbian/CustomBarnKit/blob/master/CustomGameVariables.cs#L366 to:
return NormLevelToArrayValue(useBuilding ?
(isPad ? ScenarioUpgradeableFacilities.GetFacilityLevel(SpaceCenterFacility.VAB : ScenarioUpgradeableFacilities.GetFacilityLevel(SpaceCenterFacility.SPH)
: editorNormLevel,
 isPad ? craftSizeLimitLaunchPad : craftSizeLimitRunway);

Now, of course, the full solution would be to support having the size limit node *in* the right nodes. But this will work and is dead simple. :)

And if you don't mind doing that, could you do a compile for 1.2.2? Pretty please? <3

**Comment by sarbian** [comment]
And done

**Comment by NathanKell** [comment]
Awesome! Thanks!
Is there a 1.2.2 build somewhere?

**Comment by sarbian** [comment]
It uses nothing specific to 1.3 so it should work on 1.2 as well.

**Comment by NathanKell** [comment]
Cool! I'll give it a try
