### ISSUE TITLE
Custom CommNet ranges incorrect

### ISSUE THREAD

**Issue by PhineasFreak** [sarbian/CustomBarnKit#4]
For some reason CBK does not apply the custom tracking station ranges on startup:

**[Antenna Example](https://imgur.com/QsBqM9j)**

Doing a quick MM cache fixes the antenna stats (as calculated by the current max station range).

The antenna uses the config from the RO repository: https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_SuggestedMods/Squad/RO_Squad_Communication.cfg#L91-L99

And the RSS tracking station ranges: https://github.com/KSP-RO/RealSolarSystem/blob/master/GameData/RealSolarSystem/DSN_Ranges.cfg#L17-L23

**Note:** In this example the antenna range has been changed from 32 (stated in the RO repository) to 3200. This is nonetheless trivial as it happens with both set values. In the screenshot example the range should be:

```
R = SQRT(AntennaRange * StationRange) = SQRT(3200 * 500000000000) = 40000000 m (40 Mm)
```

But it is instead **12.6 Mm** (a factor of ~3.17 low)

Happens for every antenna type (DIRECT or RELAY), under both "stock" RSS and RO.

**Comment by sarbian** [comment]
I will have a look but since CBK only replace the value of an array I doubt the problem is actually here.

**Comment by PhineasFreak** [comment]
Yay! Thank you Sarbian!

**Comment by sarbian** [comment]
I did not fully test it  so some feedback would be welcome :)

**Comment by PhineasFreak** [comment]
You were right, it still requires a reload to make the parts work. On the other hand the tracking station ranges are reported correctly by the right-click menu (not sure it did so before).
