### ISSUE TITLE
orbitDisplayMode is not an array

### ISSUE THREAD

**Issue by NathanKell** [sarbian/CustomBarnKit#6]
It looks like in the array conversion, it was missed. It's just the level to swap orbit display, instead of (like the other things) a "what is the value for this TS level". It would be Real Nice (tm) if it were instead an array, so you could specify the enum level for conics display at each TS level.

**Comment by sarbian** [comment]
Aye aye, Sir!

**Comment by NathanKell** [comment]
Sorry to ask, but the release wouldn't happen to be for 1.3.1 would it? Pretty please? <3
