### ISSUE TITLE
Switch editor button issues

### ISSUE THREAD

**Issue by siimav** [sarbian/CustomBarnKit#7]
The Switch editor button that was added in KSP 1.4 to the editor causes some serious issues with CBK. After hitting that button it looks as if the game variables somehow get reset to stock values and thus incorrect facility levels are persisted to the savegame after leaving the editor scene.
RP-1 has defined 9 upgrade levels for the tracking station. After upgrading it once, the level is set to 0.111. After using the Switch button in the editor and coming back to the space center, the value gets reset to 0 in my save. After upgrading the facility 3 times to 0.333, it gets rounded to 0.5 because stock itself only has 3 levels.

**Comment by sarbian** [comment]
Good catch. I am away on a work trip but remind me about it in a week and I ll see what I can do about it.

**Comment by sarbian** [comment]
I fixed it but I will have to back port it to KSP 1.4. Remind me about it if I haven't in a week.

**Comment by siimav** [comment]
Just a friendly reminder :)
