### ISSUE TITLE
CustomBarnKit-RO needs its own separate remote version file URL

### ISSUE THREAD

**Issue by HebaruSan** [sarbian/CustomBarnKit#9]
## Background

The `"URL"` property of a version file points to a remote copy of that version file that can be updated as needed. This allows:

- Notification of new releases
- Updates of compatibility for the current release

## Problem

Both CustomBarnKit and CustomBarnKit-RO share the same `"URL"` property:

https://github.com/sarbian/CustomBarnKit/blob/9d4c29aca395835cd06e40d2afe0167857b69a4d/CustomBarnKit/CustomBarnKit.version.in#L3

That file contains values that are not correct for CustomBarnKit-RO (according to @DRVeyl, never mind if this **is** correct):

```json
    "KSP_VERSION": {
        "MAJOR": 1,
        "MINOR": 8,
        "PATCH": 99
    },
    "KSP_VERSION_MIN": {
        "MAJOR": 1,
        "MINOR": 8,
        "PATCH": 0
    },
    "KSP_VERSION_MAX": {
        "MAJOR": 1,
        "MINOR": 8,
        "PATCH": 99
    }
```

This causes the metadata in CKAN to show CustomBarnKit-RO as compatible with KSP 1.8:

https://github.com/KSP-CKAN/CKAN-meta/blob/b6f4c9512fb8ec3b5b1ecea5fd151ac3321322f3/CustomBarnKit-RO/CustomBarnKit-RO-1.1.20.0.ckan#L3-L9

```json
    "identifier": "CustomBarnKit-RO",
    "name": "Custom Barn Kit - RO build",
    "abstract": "A small plugin to change a bunch of parameters related to career, science, the buildings upgrade cost and when various features are unlocked. Build for Realism Overhaul",
    "author": "Sarbian",
    "version": "1.1.20.0",
    "ksp_version_min": "1.8.0",
    "ksp_version_max": "1.8.99",
```

Initially reported in KSP-CKAN/NetKAN#7859.

**Comment by sarbian** [comment]
I fixed the build script and ran it. The version file URL is now the RO one.
